spring:
  application:
    name: myKanban
  datasource:
    url: jdbc:mysql://localhost:3306/kanban?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: chanhtin
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

